[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "datatypes_collection"
license = {file = "./LICENSE.txt"}
version = "0.1.0"
dependencies = [ 
   "protobuf==3.20.0"
]
